import html
import json
from .schemas import CareerReport


def _render(value):
    if value == "Not Available":
        return '<p class="unavailable">Not Available</p>'
    if isinstance(value, list):
        if not value:
            return '<p class="unavailable">Not Available</p>'
        return "<ul>" + "".join(f"<li>{_render(item)}</li>" for item in value) + "</ul>"
    if isinstance(value, dict):
        return "<div class=grid>" + "".join(
            f"<div class=field><strong>{html.escape(str(key).replace('_', ' ').title())}</strong><span>{_render(item)}</span></div>"
            for key, item in value.items()) + "</div>"
    return html.escape(str(value))


def export_html(report: CareerReport) -> bytes:
    sections = "".join(f"<section><h2>{html.escape(section.title)}</h2>{_render(section.value)}</section>" for section in report.sections)
    document = f'''<!doctype html><html><head><meta charset="utf-8"><title>Hunter AI Career Intelligence Report</title>
<style>@page{{margin:18mm}}*{{box-sizing:border-box}}body{{margin:0;color:#172033;font:14px/1.55 Arial,sans-serif;background:#f5f7fb}}.page{{max-width:900px;margin:32px auto;background:#fff;padding:52px;box-shadow:0 10px 40px #14213d14}}header{{border-bottom:5px solid #5b5ce2;padding-bottom:30px}}.brand{{color:#5b5ce2;font-weight:800;letter-spacing:.12em;font-size:13px}}h1{{font-size:36px;line-height:1.12;margin:12px 0}}h2{{font-size:18px;margin:0 0 14px;color:#24256b}}section{{border-top:1px solid #e7e9f2;padding:25px 0}}.meta{{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:25px}}.meta div,.field{{background:#f7f8ff;border-radius:8px;padding:12px}}.field strong{{display:block;font-size:11px;text-transform:uppercase;color:#5b5ce2;margin-bottom:4px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}}ul{{margin:0;padding-left:20px}}.unavailable{{color:#75809a;font-style:italic;margin:0}}footer{{color:#75809a;border-top:1px solid #e7e9f2;padding-top:18px;font-size:12px}}@media print{{body{{background:#fff}}.page{{box-shadow:none;margin:0;padding:0}}section{{break-inside:avoid}}}}</style></head><body><main class="page"><header><div class="brand">HUNTER AI</div><h1>Career Intelligence Report</h1><div class="meta"><div><strong>Candidate</strong><br>{html.escape(report.candidate_name)}</div><div><strong>Profile completion</strong><br>{report.profile_completion}%</div><div><strong>Resume parsing</strong><br>{html.escape(report.resume_parsing_status)}</div></div></header>{sections}<footer>Generated by Hunter AI · {html.escape(report.generated_at)}</footer></main></body></html>'''
    return document.encode("utf-8")

