import io
from fpdf import FPDF

class PremiumReportPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(44, 62, 80)  # Dark blue-grey
        self.cell(0, 15, 'HUNTER AI', ln=True, align='C')
        
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(52, 152, 219)  # Light blue
        self.cell(0, 10, 'AI JOB ANALYSIS REPORT', ln=True, align='C')
        self.ln(10)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Hunter AI', 0, 0, 'C')
        
    def section_title(self, num, title):
        self.ln(10)
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(255, 255, 255)
        self.set_fill_color(52, 73, 94) # Dark header background
        self.cell(0, 8, f'  {num}. {title}', ln=True, fill=True)
        self.ln(4)
        
    def key_value(self, key, value):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(44, 62, 80)
        self.cell(50, 6, f'{key}:', 0, 0)
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(0, 0, 0)
        # Using multi_cell to handle long values gracefully. 
        # Manually specify width instead of 0 to avoid "Not enough horizontal space" error
        self.multi_cell(self.epw - 50, 6, str(value))
        
    def bullet_item(self, text, icon="[+]"):
        self.set_font('Helvetica', '', 10)
        # Check icon to set color
        if icon == "[+]":
            self.set_text_color(39, 174, 96) # Green
            self.cell(10, 6, "Y ", 0, 0) # Fallback character for check
        elif icon == "[-]":
            self.set_text_color(192, 57, 43) # Red
            self.cell(10, 6, "X ", 0, 0) # Fallback character for cross
        else:
            self.set_text_color(44, 62, 80)
            self.cell(10, 6, str(icon), 0, 0)
            
        self.set_text_color(0, 0, 0)
        self.multi_cell(self.epw - 10, 6, str(text))

def generate_pdf_report(data: dict) -> bytes:
    pdf = PremiumReportPDF()
    pdf.add_page()
    
    # Overview metadata
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 6, f"Candidate: {data.get('candidate_name')}", ln=True)
    pdf.cell(0, 6, f"Generated: {data.get('generated_date')}", ln=True)
    
    # 1. TASK INFORMATION
    pdf.section_title(1, 'TASK INFORMATION')
    pdf.key_value('Task', 'AI Dashboard Summary')
    pdf.key_value('Task ID', data.get('task_id'))
    pdf.key_value('Status', data.get('status'))
    
    # 2. DASHBOARD STATISTICS
    pdf.section_title(2, 'DASHBOARD STATISTICS')
    pdf.key_value('Total Jobs Matched', str(data.get('total_matches')))
    pdf.key_value('Average Match Score', f"{data.get('avg_score')}%")
    pdf.key_value('Best Fit Score', f"{data.get('top_score')}%")
    
    # 3. TOP 5 MATCHED INTERNSHIPS
    pdf.section_title(3, 'TOP 5 MATCHED INTERNSHIPS')
    top_5 = data.get('top_5_matches', [])
    if top_5:
        for i, match in enumerate(top_5, 1):
            pdf.set_font('Helvetica', 'B', 11)
            pdf.set_text_color(41, 128, 185)
            pdf.cell(0, 6, f"#{i} - {match['job_title']}", ln=True)
            
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(44, 62, 80)
            pdf.cell(50, 6, f"Company:", 0, 0)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(pdf.epw - 50, 6, match['company'])
            
            pdf.set_text_color(44, 62, 80)
            pdf.cell(50, 6, f"Match Score:", 0, 0)
            pdf.set_text_color(39, 174, 96) # Green
            pdf.multi_cell(pdf.epw - 50, 6, f"{match['score']}%")
            
            pdf.ln(2)
    else:
        pdf.bullet_item("No job matches found yet. Upload a resume to get started.", icon="-")
        
    # 4. FREQUENT SKILL MATCHES
    pdf.section_title(4, 'TOP MATCHED SKILLS (Across roles)')
    skills = data.get('matched_skills', [])
    if skills:
        for skill in skills:
            pdf.bullet_item(skill, icon="[+]")
    else:
        pdf.bullet_item("Not Available", icon="-")
        
    # 5. FREQUENT SKILL GAPS
    pdf.section_title(5, 'TOP SKILL GAPS (Across roles)')
    gaps = data.get('skill_gaps', [])
    if gaps:
        for gap in gaps:
            pdf.bullet_item(gap, icon="[-]")
    else:
        pdf.bullet_item("None", icon="-")
        
    # 6. SUMMARY
    pdf.section_title(6, 'SUMMARY')
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(0, 0, 0)
    summary_text = f"Candidate '{data.get('candidate_name')}' has matched with {data.get('total_matches')} total opportunities with a top score of {data.get('top_score')}%. "
    if gaps:
        summary_text += f"To improve match rates, consider focusing on gaining experience in: {', '.join(gaps[:3])}."
    else:
        summary_text += "Profile looks incredibly strong for the target roles."
    pdf.multi_cell(pdf.epw, 6, summary_text)
    
    return pdf.output(dest="S")
