import io
from fpdf import FPDF

class PremiumReportPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(44, 62, 80)  # Dark blue-grey
        self.cell(0, 15, 'HUNTER AI', ln=True, align='C')
        
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(52, 152, 219)  # Light blue
        self.cell(0, 10, 'AI JOB ANALYSIS REPORT', ln=True, align='C')
        self.ln(10)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Hunter AI', 0, 0, 'C')
        
    def section_title(self, num, title):
        self.ln(10)
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(255, 255, 255)
        self.set_fill_color(52, 73, 94) # Dark header background
        self.cell(0, 8, f'  {num}. {title}', ln=True, fill=True)
        self.ln(4)
        
    def key_value(self, key, value):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(44, 62, 80)
        self.cell(50, 6, f'{key}:', 0, 0)
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(0, 0, 0)
        # Using multi_cell to handle long values (like links or notes) gracefully
        self.multi_cell(0, 6, str(value))
        
    def bullet_item(self, text, icon="[+]"):
        self.set_font('Helvetica', '', 10)
        # Check icon to set color
        if icon == "[+]":
            self.set_text_color(39, 174, 96) # Green
            self.cell(10, 6, "Y ", 0, 0) # Fallback character for check
        elif icon == "[-]":
            self.set_text_color(192, 57, 43) # Red
            self.cell(10, 6, "X ", 0, 0) # Fallback character for cross
        else:
            self.set_text_color(44, 62, 80)
            self.cell(10, 6, str(icon), 0, 0)
            
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 6, str(text))

def generate_pdf_report(data: dict) -> bytes:
    pdf = PremiumReportPDF()
    pdf.add_page()
    
    # Overview metadata
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 6, f"Candidate: {data.get('candidate_name')}", ln=True)
    pdf.cell(0, 6, f"Target Role: {data.get('target_role')}", ln=True)
    pdf.cell(0, 6, f"Generated: {data.get('generated_date')}", ln=True)
    
    # 1. TASK INFORMATION
    pdf.section_title(1, 'TASK INFORMATION')
    pdf.key_value('Task', 'AI Job Match Analysis')
    pdf.key_value('Task ID', data.get('task_id'))
    pdf.key_value('Status', data.get('status'))
    pdf.key_value('Created', data.get('generated_date'))
    
    # 2. JOB INFORMATION
    pdf.section_title(2, 'JOB INFORMATION')
    pdf.key_value('Job Title', data.get('job_title'))
    pdf.key_value('Company', data.get('company'))
    pdf.key_value('Location', data.get('location'))
    pdf.key_value('Experience Required', data.get('experience_required'))
    pdf.key_value('Job Source', data.get('job_source'))
    pdf.key_value('Job Link', data.get('job_link'))
    
    # 3. AI MATCH ANALYSIS
    pdf.section_title(3, 'AI MATCH ANALYSIS')
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 8, f"Overall Match Score: {data.get('overall_score')}%", ln=True)
    pdf.ln(2)
    
    pdf.key_value('Resume Match', f"{data.get('resume_score', 'Not Available')}%")
    pdf.key_value('Skills Match', f"{data.get('skills_score', 'Not Available')}%")
    pdf.key_value('Experience Match', f"{data.get('experience_score', 'Not Available')}%")
    pdf.key_value('Education Match', f"{data.get('education_score', 'Not Available')}%")
    
    # 4. MATCHING SKILLS
    pdf.section_title(4, 'MATCHING SKILLS')
    skills = data.get('matched_skills', [])
    if skills:
        for skill in skills:
            pdf.bullet_item(skill, icon="[+]")
    else:
        pdf.bullet_item("Not Available", icon="-")
        
    # 5. SKILL GAPS
    pdf.section_title(5, 'SKILL GAPS')
    gaps = data.get('skill_gaps', [])
    if gaps:
        for gap in gaps:
            pdf.bullet_item(gap, icon="[-]")
    else:
        pdf.bullet_item("None", icon="-")
        
    # 6. AI RECOMMENDATIONS
    pdf.section_title(6, 'AI RECOMMENDATIONS')
    recs = data.get('recommendations', [])
    if recs:
        for i, rec in enumerate(recs, 1):
            pdf.bullet_item(rec, icon=f"{i}.")
    else:
        pdf.bullet_item("No recommendations available.", icon="-")
        
    # 7. AGENT NOTES
    pdf.section_title(7, 'AGENT NOTES')
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 6, str(data.get('agent_notes', 'Not Available')))
    
    # 8. TASK STATUS
    pdf.section_title(8, 'TASK STATUS')
    pdf.key_value('Status', 'Completed')
    pdf.key_value('AI Analysis', 'Completed')
    pdf.key_value('Recommendation', 'Generated')
    
    return pdf.output(dest="S")
